### PR TITLE
Minor updates to gap8 dockerfile and readme

### PR DESCRIPTION
**Pull request by SuperN1ck**
Hey Bitcraze-Team!

I came across some minor problems when setting up the docker. I tested it with the image processing example and everything works as intended.

Cheers,
-Nick
Related Issue: https://github.com/bitcraze/AIdeck_examples/issues/17

### CODE REVIEW

**Comment by knmcguire** [comment]
Thanks! I will try out your changes soon!

So I assume that you liked using the dockerimages? I imagined that it would be handy for setting up the SDK since it is depended on. I still need to update all the examples to work on the docker image it but haven't gotten around to it.

**Comment by SuperN1ck** [comment]
Yes! The dockerimage(s) is so convenient. I already went through the normal setup on a different machine a couple of weeks ago and was happy to see that you provide the dockerimages now. With them I was able to get going in under like half an hour.

Regarding the other examples I already investigated/updated some of them like a month ago (without the docker) but got caught up with other stuff up until now. But my plan is to look into the examples again in the near future and hopefully to contribute some more soon.

**Comment by krichardsson** [comment]
Hi and thanks for the PR! 
I just wanted to add a comment on the "sudo" before each docker command. 
The use of sudo depends on how docker is installed on the machine, and the OS that is used. It is probably better to add a comment somewhere, on the lines of: "Depending on how you have installed docker on your system you may have to use sudo when calling docker".

**Comment by SuperN1ck** [comment]
I agree. I added the `sudo` throughout the readme as in the current readme it used in the first command. But I feel like using sudo shouldn't be over-empathised. So I removed it and put a note at the top linking to the official docker documentation for more information.

**Comment by knmcguire** [comment]
I added some extra information, so that the users know that they have to change the device path or the cfg file for openocd. 

Thanks a lot for your contribution !

**Comment by SuperN1ck** [comment]
Great! Thank you for your feedback :)

**Pull request merged**
