### PR TITLE
Update docker-gap8.md

### PR DESCRIPTION
**Pull request by RavenLite**
Need pass system env variable into Dockerfile.
Some related questions have been proposed:
- https://forum.bitcraze.io/viewtopic.php?f=21&t=4541
- https://forum.bitcraze.io/viewtopic.php?p=20506#p20506

### CODE REVIEW

**Comment by knmcguire** [comment]
Hi!

The line: 

`docker build --tag gapsdk:${GAP_SDK_VERSION} --build-arg GAP_SDK_VERSION .`

already works without adding the
`=$GAP_SDK_VERSION `

I just double checked this with a print out in the build so it is not necessary

**Comment by SuperN1ck** [comment]
Hey,
just a quick note regarding this issue/PR. This problem appeared for us when the user was not in the docker group and built the docker with `sudo`. After adding the user to the docker group the command in the readme works for us.

**Comment by RavenLite** [comment]
Cool.
It explains that strange phenomenon~
So, I suggest the code should work well under the most possibilities.

**Comment by knmcguire** [comment]
Hi! Since we moved the dockerfile to this repo now: https://github.com/bitcraze/docker-aideck and we are hosting the image on docker hub, I'm closing this pull request.

**Pull request closed without merging**
